name: domain-list-community

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout domain-list-community
        uses: actions/checkout@v5
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Build
        run: |-
          go build
          GOEXE=$(go env GOEXE)
          install -D --no-target-directory --verbose domain-list-community$GOEXE "${{ github.workspace }}/dist/dlc-${{ matrix.GOOS }}-${{ matrix.GOARCH }}$GOEXE"
        working-directory: domain-list-community
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
      - if: matrix.GOARCH == 'amd64' && matrix.GOOS == 'linux'
        name: Test
        run: dist/dlc-* --help
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: domain-list-community-${{ matrix.GOARCH }}-${{ matrix.GOOS }}
          path: dist
    strategy:
      matrix:
        include:
          - GOARCH: arm64
            GOOS: darwin
          - GOARCH: amd64
            GOOS: linux
          - GOARCH: amd64
            GOOS: windows
      fail-fast: false

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: domain-list-community-*
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: domain-list-community
          files: dist/*
