name: fTetWild

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout fTetWild
        uses: actions/checkout@v5
        with:
          repository: wildmeshing/fTetWild
          path: fTetWild
      - name: Configure
        run: |-
          mkdir -p -v "build"
          pushd "build"
          cmake .. -D CMAKE_BUILD_TYPE=Release
        working-directory: fTetWild
      - name: Build
        run: |-
          make --jobs
          mkdir -p -v "${{ github.workspace }}/dist"
          install -m u=rwx,go=rx -v FloatTetwild_bin "${{ github.workspace }}/dist/fTetWild-${{ runner.arch }}-${{ runner.os }}"
        working-directory: fTetWild/build
      - name: Test
        run: dist/fTetWild-* --help
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: fTetWild-${{ runner.arch }}-${{ runner.os }}
          path: dist
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: dist
          pattern: fTetWild-*
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: fTetWild
          files: dist/*
