name: PolyFEM

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout PolyFEM
        uses: actions/checkout@v4
        with:
          repository: polyfem/polyfem
          path: polyfem
      - name: Dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install libblas-dev
      - name: Configure
        run: |-
          cp -v "${{ github.workspace }}/pkg/PolyFEM/PolyFEMOptions.cmake" "PolyFEMOptions.cmake"
          mkdir -p -v "build"
          pushd "build"
          cmake .. -D CMAKE_BUILD_TYPE=Release
        working-directory: polyfem
      - name: Build
        run: |-
          make --jobs=4
          mkdir -p -v "${{ github.workspace }}/dist"
          install -m u=rwx,go=rx -v PolyFEM_bin "${{ github.workspace }}/dist/PolyFEM-${{ runner.arch }}-${{ runner.os }}"
        working-directory: polyfem/build
      - name: Help
        run: dist/PolyFEM-* --help
      - name: Tests
        run: ctest --verbose --output-on-failure
        working-directory: polyfem/build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PolyFEM-${{ runner.arch }}-${{ runner.os }}
          path: dist
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: PolyFEM-*
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: PolyFEM
          files: dist/*
